import type { PhaseQuestions } from '@/lib/domain/types';

const ts = '2026-08-26T09:00:00.000Z';

/** The questions each phase left open, and the moves it implied. */
export const PHASE_QUESTIONS: Record<number, PhaseQuestions> = {
  0: {
    items: [
      { q: 'What is your actual on-time installation rate, measured at the customer door rather than at despatch?', why: 'Our 74% is derived from review sentiment and the service log; the whole delivery case rests on the real number', who: 'Head of Service', priority: 'High', condition: 'benchmarked' },
      { q: 'What utilisation are the three plants actually running at, individually?', why: 'We have one blended figure; if the plants differ widely the opportunity is balancing, not capacity', who: 'Head of Manufacturing', priority: 'High', condition: 'benchmarked' },
      { q: 'When a customer walks out of a store without buying, what do they say the reason was?', why: 'We have assumed lead time is the main objection, and the whole promise case is built on that assumption', who: 'Head of Retail', priority: 'Medium', condition: 'assumption' },
    ],
    covered: [
      { q: 'What is the current revenue and growth rate?', source: 'FY26 annual filing, page 7' },
      { q: 'How many manufacturing units and stores are operating?', source: 'company website, about page' },
    ],
    sug: [
      { act: 'Get plant-level utilisation before the leadership session, not the blended number', why: 'If one plant is at 84% and another at 51%, the entire diagnosis changes from capacity to balancing', owner: 'Analyst', when: 'Before the leadership session' },
      { act: 'Open on margin, not on growth', why: 'Fourth of five on EBITDA while growing at 24.6% is the fact that will hold a founder-led room', owner: 'Engagement lead', when: 'Before the leadership session' },
    ],
    ts,
  },
  1: {
    items: [
      { q: 'Can we have 12 months of promised date against actual installation date, at order level?', why: 'Phase 2 cannot size the delivery pool without the distribution, not just the average', who: 'Head of Service', priority: 'High', condition: 'next-phase-input' },
      { q: 'Who owns the on-time number today — Manufacturing, Service, or nobody?', why: 'A missed date is absorbed by Service, so Manufacturing never feels it; Phase 2 needs to route to an owner', who: 'Co-founder and CEO', priority: 'High', condition: 'no-owner' },
    ],
    covered: [
      { q: 'What is the three-year ambition?', source: 'leadership session, 20 Aug' },
      { q: 'What happened to the SAP APS module licensed in 2023?', source: 'leadership session, 20 Aug' },
      { q: 'Is a second shift available this year?', source: 'leadership session — ruled out by the CFO' },
    ],
    sug: [
      { act: 'Scope Phase 2 to manufacturing, service and procurement only', why: 'Those three carry Rs 103 Cr of the Rs 117 Cr identified; retail and growth do not earn the time', owner: 'Engagement lead', when: 'This week' },
      { act: 'Never describe this as a planning system', why: 'The 2023 APS module was licensed, never went live, and is well known internally as a failure', owner: 'Engagement lead', when: 'Before Phase 2 interviews' },
      { act: 'Bring the Head of Manufacturing into the network design from the first session', why: 'He reads central planning as losing control of his plants, and he can stop this on his own', owner: 'Strategy lead', when: 'Before Phase 2' },
    ],
    ts,
  },
  2: {
    items: [
      { q: 'Can we follow one made-to-order unit from store checkout to installed in the customer home?', why: 'Phase 3 needs a traced unit of work across all three plants, not a process description', who: 'Head of Manufacturing', priority: 'High', condition: 'next-phase-input' },
      { q: 'How clean is the SAP master data on capacity and BOM across the three plants?', why: 'It is the reason the 2023 APS module never went live, and it decides whether the promise agent is feasible at all', who: 'Head of Manufacturing', priority: 'High', condition: 'assumption' },
    ],
    covered: [{ q: 'How many orders flow through the three plants a year?', source: 'SAP production export, shared 27 Aug — 412,000' }],
    sug: [
      { act: 'Trace one order end to end from the Bengaluru store through Hosur to installation', why: 'Rs 34 Cr sits on a handoff between a POS and three spreadsheets that nobody has ever mapped', owner: 'FDE', when: 'This week' },
      { act: 'Audit SAP master data quality before Phase 4 costs anything', why: 'Every future-state step assumes a usable capacity model, and this is exactly what killed the last attempt', owner: 'Solution architect', when: 'Before Phase 3 closes' },
    ],
    ts,
  },
  3: {
    items: [
      { q: 'Would Manufacturing accept a date generated by an agent being shown to a customer before a human sees it?', why: 'The entire promise redesign depends on this answer, and it is a control question, not a technical one', who: 'Head of Manufacturing', priority: 'High', condition: 'assumption' },
      { q: 'What service level are you willing to publish per SKU class, and who signs it?', why: 'The planning agent needs a target to optimise against; without one it has no objective function', who: 'Chief Financial Officer', priority: 'High', condition: 'no-owner' },
    ],
    covered: [
      { q: 'How many systems does one order touch?', source: 'traced at Hosur, 30 Aug — four' },
      { q: 'How often is the monthly plan changed mid-month?', source: 'observed and confirmed by the planner — 71% of months' },
    ],
    sug: [
      { act: 'Sequence installation before promising in the roadmap', why: 'It is a bigger customer-visible win, needs no master data cleanup, and it buys the credibility to attempt the plan', owner: 'Solution architect', when: 'Before the design session' },
      { act: 'Show the promise as a range before showing it as a date', why: 'It de-risks the first release and gives Manufacturing a way to say yes without giving up control at once', owner: 'Engagement lead', when: 'At the design session' },
    ],
    ts,
  },
  4: {
    items: [
      { q: 'Are the 340 installation crews contracted in a way that lets us assign them by skill rather than by availability?', why: 'The installation case assumes skill-matched assignment is contractually possible, and nobody has confirmed it', who: 'Head of Service', priority: 'High', condition: 'assumption' },
    ],
    covered: [
      { q: 'Can SAP expose live capacity to an external agent?', source: 'design session, 2 Sep — confirmed, read-only to start' },
      { q: 'Can the POS call an external service before showing a date?', source: 'design session — yes, with a fallback to the fixed date' },
    ],
    sug: [
      { act: 'Design the POS fallback path explicitly, and test it first', why: 'A checkout that cannot show a date is worse than one showing a wrong date; this is the only customer-facing risk', owner: 'Solution architect', when: 'Before Phase 5' },
      { act: 'Cost master data cleanup as a separate line, not inside the agent', why: 'It is the largest uncertainty in the estimate and the thing most likely to slip the Q3 date', owner: 'FDE', when: 'Before Phase 5' },
    ],
    ts,
  },
  5: {
    items: [
      { q: 'Does Rs 14.6 Cr sit inside the technology budget, or does it compete with store expansion?', why: 'Decides whether both NOW initiatives start together or the portfolio stretches over three years', who: 'Chief Financial Officer', priority: 'High', condition: 'next-phase-input' },
      { q: 'Who will own the on-time installation number once the agent is live?', why: 'The Rs 28 Cr case still has no accountable owner, and it is the same gap Phase 1 raised and Phase 3 repeated', who: 'Co-founder and CEO', priority: 'High', condition: 'no-owner' },
      { q: 'Will Procurement accept an independent read of purchase price against the index?', why: 'The Rs 22 Cr buying case is entirely ours; Procurement disputes it and it cannot be funded while that stands', who: 'Head of Procurement', priority: 'Medium', condition: 'benchmarked' },
    ],
    covered: [{ q: 'What hurdle rate should the cases be tested against?', source: 'CFO review, 3 Sep — 20% IRR' }],
    sug: [
      { act: 'Take installation to the board alone, with the return channel as the second slide', why: 'Seven-month payback on a customer-visible number is the easiest yes, and it needs no master data work', owner: 'Engagement lead', when: 'At the closing session' },
      { act: 'Make SAP master data cleanup a funded workstream, not a dependency', why: 'It gates Rs 34 Cr and it has already killed one attempt at exactly this; it will not happen as a side task', owner: 'Strategy lead', when: 'At the closing session' },
    ],
    ts,
  },
};
